
CREATE TABLE STAFF_INFO (
	STAFF_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STAFF_NAME VARCHAR(500) NOT NULL			#직원명
	, STAFF_TEL VARCHAR(15)							#연락처
	, STAFF_EMAIL VARCHAR(50)						#이메일
	, STAFF_ROLE VARCHAR(100) DEFAULT 'STAFF'	#권한
	, STAFF_JOB VARCHAR(50)							#직급
	, STAFF_TASK VARCHAR(100)						#업무
	, STAFF_STATUS VARCHAR(50)						#상태 ('WORKING', 'REST', 'LEAVE')
	, JOIN_DATE DATE
);

CREATE TABLE CLASS_ROOM (
	CLASS_ROOM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ROOM_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE CLASS_INFO (
	CLASS_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLASS_NAME VARCHAR(100) NOT NULL						#과정명
	, JOB_CLASS VARCHAR(50) NOT NULL							#직종
	, CLASS_TYPE VARCHAR(50) NOT NULL						#과정 유형
	, START_DATE DATE NOT NULL									#시작일
	, END_DATE DATE NOT NULL									#종료일
	, TOTAL_STUDY_DAY INT NOT NULL							#수업일수
	, CLASS_STATUS VARCHAR(50) NOT NULL						#과정상태 (시작 전, 진행 중, 종료)
	, CLASS_QUOTA INT NOT NULL DEFAULT 0					#모집 정원
	, CONFIRM_STU_CNT INT NOT NULL DEFAULT 0				#실시인원
	, JOIN_STU_CNT INT NOT NULL DEFAULT 0					#참여인원
	, DROP_STU_CNT INT  DEFAULT 0								#중탈인원
	, COMPLETE_STU_CNT INT  DEFAULT 0						#수료인원
	, EARLY_COMPLETE_CNT	INT DEFAULT 0						#80%수료인원
	, EARLY_EMPLOY_CNT INT DEFAULT 0							#80%취업인원
	, RECRUIT_RATE FLOAT NOT NULL	 DEFAULT 0.0			#모집률
	, STAFF_NUM INT REFERENCES STAFF_INFO (STAFF_NUM)	#담당 직원(강사) 번호
	, CLASS_COMMENT VARCHAR(200)								#비고
);

ALTER TABLE CLASS_INFO 
CHANGE JOINNING_CSTU_CNT JOIN_STU_CNT INT NOT NULL	DEFAULT 0;

CREATE TABLE CLASS_OPER_INFO (
	CLASS_OPER_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STAFF_NUM INT NOT NULL REFERENCES STAFF_INFO (STAFF_NUM)			#담당강사 번호
	, CLASS_ROOM INT NOT NULL REFERENCES CLASS_ROOM (CLASS_ROOM_NUM)	#강의실명
	, STUDY_DAY VARCHAR(30) NOT NULL												#수업요일
	, START_TIME TIME																	#수업 시작 시간
	, END_TIME TIME																	#수업 종료 시간
	, CLASS_NUM INT NOT NULL REFERENCES CLASS_INFO (CLASS_NUM)			#과정 번호
	, IS_USING VARCHAR(3) NOT NULL 												#적용 중 여부

);