
#직종
CREATE TABLE JOB_TYPE (
	JOB_NUM INT PRIMARY KEY AUTO_INCREMENT
	, JOB_NAME VARCHAR(30) NOT NULL
	, JOB_ORDER INT NOT NULL
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);


INSERT INTO JOB_TYPE VALUES (1, '응용SW엔지니어링', 1);
INSERT INTO JOB_TYPE VALUES (2, '광고콘텐츠제작', 2);
INSERT INTO JOB_TYPE VALUES (3, '편집디자인', 3);
INSERT INTO JOB_TYPE VALUES (4, '실내디자인', 4);
INSERT INTO JOB_TYPE VALUES (5, '실내건축디자인', 5);
INSERT INTO JOB_TYPE VALUES (6, '세무', 6);
INSERT INTO JOB_TYPE VALUES (7, '사무행정', 7);

#과정 유형
CREATE TABLE CLASS_TYPE (
	CLASS_TYPE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLASS_TYPE_NAME VARCHAR(30) NOT NULL
	, CLASS_TYPE_ORDER INT NOT NULL
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);

INSERT INTO CLASS_TYPE VALUES (1, '국기', 1);
INSERT INTO CLASS_TYPE VALUES (2, 'KDT', 2);
INSERT INTO CLASS_TYPE VALUES (3, '산대특', 3);
INSERT INTO CLASS_TYPE VALUES (4, '계좌제', 4);
INSERT INTO CLASS_TYPE VALUES (5, '근로자', 5);

#강의실
ALTER TABLE class_room ADD COLUMN CLASS_ROOM_ORDER INT NOT NULL;
CREATE TABLE CLASS_ROOM (
	CLASS_ROOM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLASS_ROOM_NAME VARCHAR(30) NOT NULL
	, CLASS_ROOM_ORDER INT NOT NULL
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);

INSERT INTO class_room VALUES (1, '201호', 1);
INSERT INTO class_room VALUES (2, '202호', 2);
INSERT INTO class_room VALUES (3, '301호', 3);
INSERT INTO class_room VALUES (4, '302호', 4);
INSERT INTO class_room VALUES (5, '303호', 5);
INSERT INTO class_room VALUES (6, '304호', 6);
INSERT INTO class_room VALUES (7, '305호', 7);
INSERT INTO class_room VALUES (8, '401호', 8);
INSERT INTO class_room VALUES (9, '402호', 9);
INSERT INTO class_room VALUES (10, '403호', 10);
INSERT INTO class_room VALUES (11, '404호', 11);


ALTER TABLE STAFF_INFO ADD COLUMN STAFF_ORDER INT NOT NULL;
CREATE TABLE STAFF_INFO (
	STAFF_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STAFF_NAME VARCHAR(500) NOT NULL			#직원명
	, STAFF_TEL VARCHAR(15)							#연락처
	, STAFF_EMAIL VARCHAR(50)						#이메일
	, STAFF_ROLE VARCHAR(100) DEFAULT 'STAFF'	#권한 USER, 
	, STAFF_JOB VARCHAR(50)							#직급
	, STAFF_TASK VARCHAR(100)						#업무
	, STAFF_STATUS VARCHAR(50)						#상태 ('WORKING', 'REST', 'LEAVE')
	, JOIN_DATE DATE
	, STAFF_ORDER INT NOT NULL
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);

INSERT INTO staff_info VALUES (1, '김형진', '010-3058-7733', 'hyungjin099@kakao.com', 'USER', '팀장', '강사', 'WORKING', SYSDATE(), 1);
INSERT INTO staff_info VALUES (2, '김영철', '010-1111-2222', 'qloqlo@kakao.com', 'USER', '팀장', '강사', 'WORKING', SYSDATE(), 2);
INSERT INTO staff_info VALUES (3, '천금채', '010-3333-4444', 'space@kakao.com', 'USER', '팀원', '강사', 'WORKING', SYSDATE(), 3);
commit;


DROP TABLE class_info;
CREATE TABLE CLASS_INFO (
	CLASS_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLASS_NAME VARCHAR(100) NOT NULL									#과정명
	, JOB_NUM INT REFERENCES job_type (JOB_NUM)						#직종번호
	, CLASS_TYPE_NUM INT REFERENCES class_type (CLASS_TYPE_NUM)	#과정 유형 번호 
	, START_DATE DATE NOT NULL												#시작일
	, END_DATE DATE NOT NULL												#종료일
	, TOTAL_STUDY_DAY INT NOT NULL										#수업일수
	, CLASS_STATUS VARCHAR(50) NOT NULL									#과정상태 (시작 전, 진행 중, 종료)
	, CLASS_QUOTA INT NOT NULL DEFAULT 0								#모집 정원
	, CONFIRM_STU_CNT INT NOT NULL DEFAULT 0							#실시인원
	, JOIN_STU_CNT INT NOT NULL DEFAULT 0								#참여인원
	, DROP_STU_CNT INT  DEFAULT 0											#중탈인원
	, COMPLETE_STU_CNT INT  DEFAULT 0									#수료인원
	, EARLY_COMPLETE_CNT	INT DEFAULT 0									#80%수료인원
	, EARLY_EMPLOY_CNT INT DEFAULT 0										#80%취업인원
	, RECRUIT_RATE FLOAT NOT NULL	 DEFAULT 0.0						#모집률
	, STAFF_NUM INT REFERENCES STAFF_INFO (STAFF_NUM)				#담당 직원(강사) 번호
	, CLASS_COMMENT VARCHAR(200)											#비고
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);

ALTER TABLE CLASS_INFO 
CHANGE JOINNING_CSTU_CNT JOIN_STU_CNT INT NOT NULL	DEFAULT 0;

DROP TABLE class_oper_info;

CREATE TABLE CLASS_OPER_INFO (
	CLASS_OPER_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STAFF_NUM INT NOT NULL REFERENCES STAFF_INFO (STAFF_NUM)				#담당강사 번호
	, CLASS_ROOM_NUM INT NOT NULL REFERENCES CLASS_ROOM (CLASS_ROOM_NUM)	#강의실명
	, STUDY_DAY VARCHAR(30) NOT NULL													#수업요일
	, STUDY_HOUR INT NOT NULL															#일일 수업 시간
	, START_TIME TIME NOT NULL															#수업 시작 시간
	, END_TIME TIME NOT NULL															#수업 종료 시간
	, CLASS_NUM INT NOT NULL REFERENCES CLASS_INFO (CLASS_NUM)				#과정 번호
	, IS_USING VARCHAR(3) NOT NULL 													#적용 중 여부
);