DROP TABLE IF EXISTS ENROLL_INFO;
DROP TABLE IF EXISTS consult_info;
DROP TABLE IF EXISTS STU_INFO;
DROP TABLE IF EXISTS class_oper_info;
DROP TABLE IF EXISTS class_info;
DROP TABLE IF EXISTS class_room;
DROP TABLE IF EXISTS staff_info;
DROP TABLE IF EXISTS CLASS_TYPE;
DROP TABLE IF EXISTS JOB_TYPE;



#직종
CREATE TABLE JOB_TYPE (
	JOB_NUM INT PRIMARY KEY AUTO_INCREMENT
	, JOB_NAME VARCHAR(30) NOT NULL UNIQUE
	, JOB_ORDER INT NOT NULL UNIQUE
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);


INSERT INTO JOB_TYPE VALUES (1, '응용SW엔지니어링', 1, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO JOB_TYPE VALUES (2, '광고콘텐츠제작', 2, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO JOB_TYPE VALUES (3, '편집디자인', 3, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO JOB_TYPE VALUES (4, '실내디자인', 4, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO JOB_TYPE VALUES (5, '실내건축디자인', 5, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO JOB_TYPE VALUES (6, '세무', 6, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO JOB_TYPE VALUES (7, '사무행정', 7, 'admin', NULL, SYSDATE(), NULL);

#과정 유형
CREATE TABLE CLASS_TYPE (
	CLASS_TYPE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLASS_TYPE_NAME VARCHAR(30) NOT NULL UNIQUE
	, CLASS_TYPE_ORDER INT NOT NULL UNIQUE
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);

INSERT INTO CLASS_TYPE VALUES (1, '국기', 1, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO CLASS_TYPE VALUES (2, 'KDT', 2, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO CLASS_TYPE VALUES (3, '산대특', 3, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO CLASS_TYPE VALUES (4, '계좌제', 4, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO CLASS_TYPE VALUES (5, '근로자', 5, 'admin', NULL, SYSDATE(), NULL);

#강의실
CREATE TABLE CLASS_ROOM (
	CLASS_ROOM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLASS_ROOM_NAME VARCHAR(30) NOT NULL UNIQUE
	, CLASS_ROOM_ORDER INT NOT NULL UNIQUE
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);

INSERT INTO class_room VALUES (1, '201호', 1, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO class_room VALUES (2, '202호', 2, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO class_room VALUES (3, '301호', 3, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO class_room VALUES (4, '302호', 4, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO class_room VALUES (5, '303호', 5, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO class_room VALUES (6, '304호', 6, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO class_room VALUES (7, '305호', 7, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO class_room VALUES (8, '401호', 8, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO class_room VALUES (9, '402호', 9, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO class_room VALUES (10, '403호', 10, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO class_room VALUES (11, '404호', 11, 'admin', NULL, SYSDATE(), NULL);

#직원정보
CREATE TABLE STAFF_INFO (
	STAFF_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STAFF_NAME VARCHAR(500) NOT NULL			#직원명
	, STAFF_TEL VARCHAR(15)	UNIQUE				#연락처
	, STAFF_EMAIL VARCHAR(50) UNIQUE				#이메일
	, STAFF_ROLE VARCHAR(100) DEFAULT 'STAFF'	#권한 USER, 
	, STAFF_JOB VARCHAR(50)							#직급
	, STAFF_TASK VARCHAR(100)						#업무
	, STAFF_STATUS VARCHAR(50)						#상태 ('WORKING', 'REST', 'LEAVE')
	, NICK_NAME VARCHAR(20)	UNIQUE						#별명, 상담직 전용
	, JOIN_DATE DATE
	, STAFF_ORDER INT NOT NULL UNIQUE
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);



INSERT INTO staff_info VALUES (1, '김형진', '010-3058-7733', 'hyungjin099@kakao.com', 'USER', '팀장', '강사', 'WORKING', NULL, SYSDATE(), 1, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO staff_info VALUES (2, '김영철', '010-1111-2222', 'qloqlo@kakao.com', 'USER', '팀장', '강사', 'WORKING', NULL, SYSDATE(), 2, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO staff_info VALUES (3, '천금채', '010-3333-4444', 'space1@kakao.com', 'USER', '팀원', '강사', 'WORKING', NULL, SYSDATE(), 3, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO staff_info VALUES (4, '김희경', '010-3331-4444', 'space2@kakao.com', 'USER', '팀장', '영업', 'WORKING',  '닉네임1', SYSDATE(), 4, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO staff_info VALUES (5, '최지운', '010-3332-4444', 'space3@kakao.com', 'USER', '팀원', '영업', 'WORKING', '닉네임2', SYSDATE(), 5, 'admin', NULL, SYSDATE(), NULL);
INSERT INTO staff_info VALUES (6, '김예림', '010-3335-4444', 'space4@kakao.com', 'USER', '팀원', '영업', 'WORKING', '닉네임3', SYSDATE(), 6, 'admin', NULL, SYSDATE(), NULL);

CREATE TABLE CLASS_INFO (
	CLASS_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLASS_NAME VARCHAR(100) NOT NULL									#과정명
	, JOB_NUM INT REFERENCES job_type (JOB_NUM)						#직종번호
	, CLASS_TYPE_NUM INT REFERENCES class_type (CLASS_TYPE_NUM)	#과정 유형 번호 
	, START_DATE DATE NOT NULL												#시작일
	, END_DATE DATE NOT NULL												#종료일
	, TOTAL_STUDY_DAY INT NOT NULL										#수업일수
	, TOTAL_STUDY_HOUR INT NOT NULL										#전체수업시간
	, CLASS_STATUS VARCHAR(50) NOT NULL DEFAULT '모집 중'			#과정상태 (모집 중, 진행 중, 종료)
	, CLASS_QUOTA INT NOT NULL DEFAULT 0								#모집 정원
	, CONFIRM_STU_CNT INT NOT NULL DEFAULT 0							#실시인원
	, JOIN_STU_CNT INT NOT NULL DEFAULT 0								#참여인원
	, DROP_STU_CNT INT  DEFAULT 0											#중탈인원
	, COMPLETE_STU_CNT INT  DEFAULT 0									#수료인원
	, EARLY_COMPLETE_CNT	INT DEFAULT 0									#80%수료인원
	, EARLY_EMPLOY_CNT INT DEFAULT 0										#80%취업인원
	, RECRUIT_RATE FLOAT NOT NULL	 DEFAULT 0.0						#모집률
	, CLASS_COMMENT VARCHAR(200)											#비고
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);


CREATE TABLE CLASS_OPER_INFO (
	CLASS_OPER_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STAFF_NUM INT NOT NULL REFERENCES STAFF_INFO (STAFF_NUM)				#담당강사 번호
	, CLASS_ROOM_NUM INT NOT NULL REFERENCES CLASS_ROOM (CLASS_ROOM_NUM)	#강의실번호
	, STUDY_DAY VARCHAR(30) NOT NULL													#수업요일
	, STUDY_HOUR INT NOT NULL															#일일 수업 시간
	, START_TIME VARCHAR(10) NOT NULL												#수업 시작 시간
	, END_TIME VARCHAR(10) NOT NULL													#수업 종료 시간
	, CLASS_NUM INT NOT NULL REFERENCES CLASS_INFO (CLASS_NUM)				#과정 번호
	, IS_USING VARCHAR(3) NOT NULL DEFAULT 'Y'									#적용 중 여부
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);

# DROP TABLE STU_INFO;
# 기본 학생 정보
CREATE TABLE STU_INFO (
	STU_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STU_NAME VARCHAR(20) NOT NULL
	, STU_BIRTHDAY VARCHAR(20) NOT NULL
	, STU_PHONE VARCHAR(20) NOT NULL
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);

#DROP TABLE enroll_info;

# 수강 데이터
CREATE TABLE ENROLL_INFO (
	ENROLL_NUM INT PRIMARY KEY
	, CLASS_NUM INT NOT NULL REFERENCES class_info (CLASS_NUM)
	, STU_NUM INT NOT NULL REFERENCES STU_INFO (STU_NUM)
	, STU_STATUS VARCHAR(30) NOT NULL DEFAULT '수강 등록'  #수강 등록,수강 중,수강 철회,수료,중도탈락, 80%수료, 80% 취업 
	, MANAGER_NUM INT NOT NULL REFERENCES staff_info (STAFF_NUM)	#담당자
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);


#수강 상담 데이터
CREATE TABLE CONSULT_INFO (
	CONSULT_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STU_NUM INT NOT NULL REFERENCES STU_INFO (STU_NUM)
	, MANAGER_NUM INT NOT NULL REFERENCES staff_info (STAFF_NUM)	#담당자
	, CONSULT_CONTENT VARCHAR(2000)
	, CLASS_NUM INT NOT NULL REFERENCES class_info (CLASS_NUM)
	, CONSULT_STATUS VARCHAR(10) NOT NULL DEFAULT '미정' #미정 '등록 불확실' 가능성50% '등록 확정' 취소
	, CONSULT_TYPE VARCHAR(10) #실업자 재직자
	, SUPPORT_TYPE VARCHAR(10) #일반 국1, 국2
	, HRD_STATUS VARCHAR(15) #실업자 HRD선발, 재직자 HRD대기, 재직자 HRD선발
	, CONSULT_GRADE VARCHAR(5) #A, B, C
	, CUSTOM_ROWS JSON CHECK (JSON_VALID(CUSTOM_ROWS)),
	, ATTITUDE_SCORE INT #성향태도 점수
	, ATTENDANCE_SCORE INT # 출결예측 점수
	, MIND_SCORE INT # #수강의지 점수
	, JOB_SCORE INT # 취업역량 점수
	, TOTAL_SCORE INT #점수 합
	, CREATE_USER VARCHAR(50)
	, UPDATE_USER VARCHAR(50)
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
	, UPDATE_DATE DATETIME
);


COMMIT;
